language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed danielshow/udagram-api-feed:v3
  - docker tag udagram-api-user danielshow/udagram-api-user:v3
  - docker tag udagram-api-user danielshow/udagram-reverseproxy:v3
  - docker tag udagram-frontend danielshow/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push danielshow/udagram-api-feed:v3
  - docker push danielshow/udagram-api-user:v3
  - docker push danielshow/udagram-reverseproxy:v3
  - docker push danielshow/udagram-frontend:v3

